// Code generated by tools/daogen. DO NOT EDIT.
// 为 DAO 合约各 op 生成类型化 payload 构建函数。注意：dao_call 现已使用 model.DaoCall protobuf，
// 提交时需将 proto 序列化后做 base64 编码作为 payload；本包 Payload 为旧版 JSON 形态，仅作参考或需另行转换为 proto。

package dao

import "encoding/json"

// Payload 为旧版 JSON 形态；dao_call 现已使用 model.DaoCall protobuf，payload 需为 base64(proto)。
type Payload struct {
  Op string `json:"op"`
  InitialMembers []MemberInput `json:"initial_members,omitempty"`
  PublicJoin     *bool   `json:"public_join,omitempty"`
  SudoAccount    []byte  `json:"sudo_account,omitempty"`
  DefaultTrack   *TrackInput `json:"default_track,omitempty"`
  NewUser        []byte  `json:"new_user,omitempty"`
  Balance        string  `json:"balance,omitempty"` // u128 十进制
  ProposalId     uint32  `json:"proposal_id,omitempty"`
  TrackId        uint32  `json:"track_id,omitempty"`
  Call           *CallInput `json:"call,omitempty"`
  Amount         string  `json:"amount,omitempty"`
  OpinionYes     bool    `json:"opinion_yes,omitempty"`
  LockAmount     string  `json:"lock_amount,omitempty"`
  VoteId         uint64  `json:"vote_id,omitempty"`
  To             []byte  `json:"to,omitempty"`
  Value          string  `json:"value,omitempty"`
  Spender        []byte  `json:"spender,omitempty"`
  From           []byte  `json:"from,omitempty"`
  SpendId        uint64  `json:"spend_id,omitempty"`
  Track          *TrackInput `json:"track,omitempty"`
}

type MemberInput struct { Account []byte `json:"account"`; Balance string `json:"balance"` }
type TrackInput struct {
  Name string `json:"name"`
  PreparePeriod uint32 `json:"prepare_period"`
  MaxDeciding   uint32 `json:"max_deciding"`
  ConfirmPeriod uint32 `json:"confirm_period"`
  DecisionPeriod uint32 `json:"decision_period"`
  MinEnactmentPeriod uint32 `json:"min_enactment_period"`
  DecisionDeposit string `json:"decision_deposit"`
  MaxBalance     string `json:"max_balance"`
}
type CallInput struct {
  Contract []byte `json:"contract,omitempty"`
  Selector []byte `json:"selector,omitempty"`
  Input    []byte `json:"input,omitempty"`
  Amount   string `json:"amount,omitempty"`
  RefTimeLimit uint64 `json:"ref_time_limit,omitempty"`
  AllowReentry bool   `json:"allow_reentry,omitempty"`
}

// MustPayload 将 p 序列化为 JSON，用于 dao_call(caller, payload)。
func MustPayload(p Payload) string { b, _ := json.Marshal(p); return string(b) }

// PayloadDaoAddTrack 构建 op dao_add_track 的 payload，返回 JSON 字符串。
func PayloadDaoAddTrack(p Payload) string { p.Op = "dao_add_track"; return MustPayload(p) }

// PayloadDaoApprove 构建 op dao_approve 的 payload，返回 JSON 字符串。
func PayloadDaoApprove(p Payload) string { p.Op = "dao_approve"; return MustPayload(p) }

// PayloadDaoCancelProposal 构建 op dao_cancel_proposal 的 payload，返回 JSON 字符串。
func PayloadDaoCancelProposal(p Payload) string { p.Op = "dao_cancel_proposal"; return MustPayload(p) }

// PayloadDaoCancelVote 构建 op dao_cancel_vote 的 payload，返回 JSON 字符串。
func PayloadDaoCancelVote(p Payload) string { p.Op = "dao_cancel_vote"; return MustPayload(p) }

// PayloadDaoDepositProposal 构建 op dao_deposit_proposal 的 payload，返回 JSON 字符串。
func PayloadDaoDepositProposal(p Payload) string { p.Op = "dao_deposit_proposal"; return MustPayload(p) }

// PayloadDaoExecProposal 构建 op dao_exec_proposal 的 payload，返回 JSON 字符串。
func PayloadDaoExecProposal(p Payload) string { p.Op = "dao_exec_proposal"; return MustPayload(p) }

// PayloadDaoInit 构建 op dao_init 的 payload，返回 JSON 字符串。
func PayloadDaoInit(p Payload) string { p.Op = "dao_init"; return MustPayload(p) }

// PayloadDaoJoin 构建 op dao_join 的 payload，返回 JSON 字符串。
func PayloadDaoJoin(p Payload) string { p.Op = "dao_join"; return MustPayload(p) }

// PayloadDaoLeave 构建 op dao_leave 的 payload，返回 JSON 字符串。
func PayloadDaoLeave(p Payload) string { p.Op = "dao_leave"; return MustPayload(p) }

// PayloadDaoLeaveWithBurn 构建 op dao_leave_with_burn 的 payload，返回 JSON 字符串。
func PayloadDaoLeaveWithBurn(p Payload) string { p.Op = "dao_leave_with_burn"; return MustPayload(p) }

// PayloadDaoPayout 构建 op dao_payout 的 payload，返回 JSON 字符串。
func PayloadDaoPayout(p Payload) string { p.Op = "dao_payout"; return MustPayload(p) }

// PayloadDaoPublicJoin 构建 op dao_public_join 的 payload，返回 JSON 字符串。
func PayloadDaoPublicJoin(p Payload) string { p.Op = "dao_public_join"; return MustPayload(p) }

// PayloadDaoSetDefaultTrack 构建 op dao_set_default_track 的 payload，返回 JSON 字符串。
func PayloadDaoSetDefaultTrack(p Payload) string { p.Op = "dao_set_default_track"; return MustPayload(p) }

// PayloadDaoSetPublicJoin 构建 op dao_set_public_join 的 payload，返回 JSON 字符串。
func PayloadDaoSetPublicJoin(p Payload) string { p.Op = "dao_set_public_join"; return MustPayload(p) }

// PayloadDaoSpend 构建 op dao_spend 的 payload，返回 JSON 字符串。
func PayloadDaoSpend(p Payload) string { p.Op = "dao_spend"; return MustPayload(p) }

// PayloadDaoSubmitProposal 构建 op dao_submit_proposal 的 payload，返回 JSON 字符串。
func PayloadDaoSubmitProposal(p Payload) string { p.Op = "dao_submit_proposal"; return MustPayload(p) }

// PayloadDaoSubmitVote 构建 op dao_submit_vote 的 payload，返回 JSON 字符串。
func PayloadDaoSubmitVote(p Payload) string { p.Op = "dao_submit_vote"; return MustPayload(p) }

// PayloadDaoTransfer 构建 op dao_transfer 的 payload，返回 JSON 字符串。
func PayloadDaoTransfer(p Payload) string { p.Op = "dao_transfer"; return MustPayload(p) }

// PayloadDaoTransferFrom 构建 op dao_transfer_from 的 payload，返回 JSON 字符串。
func PayloadDaoTransferFrom(p Payload) string { p.Op = "dao_transfer_from"; return MustPayload(p) }

// PayloadDaoUnlock 构建 op dao_unlock 的 payload，返回 JSON 字符串。
func PayloadDaoUnlock(p Payload) string { p.Op = "dao_unlock"; return MustPayload(p) }

