package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"
	"time"

	"github.com/vektah/gqlparser/v2/gqlerror"
	"github.com/wetee-dao/tee-dsecret/pkg/model"
	sidechain "github.com/wetee-dao/tee-dsecret/side-chain"
)

// StartEpoch is the resolver for the start_epoch field.
func (r *mutationResolver) StartEpoch(ctx context.Context) (bool, error) {
	sidechain.SubmitTx(&model.Tx{
		Payload: &model.Tx_Empty{
			Empty: time.Now().Unix(),
		},
	})

	return true, nil
}

// Validators is the resolver for the validators field.
func (r *queryResolver) Validators(ctx context.Context) ([]string, error) {
	validators, _, err := sideChain.GetValidators()
	if err != nil {
		return nil, gqlerror.Errorf("GetValidators:" + err.Error())
	}

	list := make([]string, 0, len(validators))
	for _, v := range validators {
		pub := model.PubKeyFromByte(v.Pubkey)
		list = append(list, pub.SS58())
	}
	return list, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
