package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"
	"time"

	"github.com/vektah/gqlparser/v2/gqlerror"
	"github.com/wetee-dao/tee-dsecret/pkg/model"
	"github.com/wetee-dao/tee-dsecret/pkg/util"
)

// StartEpoch is the resolver for the start_epoch field.
// 使用 DKG Signer 签名交易并提交空块，触发新区块生成
func (r *mutationResolver) StartEpoch(ctx context.Context) (bool, error) {
	// 创建空块交易
	call := &model.SysCall{
		Payload: &model.SysCall_Empty{
			Empty: time.Now().Unix(),
		},
	}

	// 提交交易
	if err := sideChain.SubmitCallFromNode(call); err != nil {
		return false, gqlerror.Errorf("SubmitTx: %v", err)
	}

	return true, nil
}

// ChainInfo is the resolver for the chain_info field.
func (r *queryResolver) ChainInfo(ctx context.Context) ([]*model.ChainInfo, error) {
	chainEnv := util.GetEnv("CHAIN_ENV", "local")
	chainConfig := model.GetChainConfig(chainEnv)
	if chainConfig == nil {
		return nil, gqlerror.Errorf("%s", "ChainInfo is nil")
	}

	return []*model.ChainInfo{
		{
			IsMain:         true,
			CloudContract:  chainConfig.CloudAddress,
			SubnetContract: chainConfig.SubnetAddress,
			NetworkLabel:   chainConfig.NetworkLabel,
		},
	}, nil
}

// Validators is the resolver for the validators field.
func (r *queryResolver) Validators(ctx context.Context) ([]string, error) {
	validators, _, err := sideChain.GetValidators()
	if err != nil {
		return nil, gqlerror.Errorf("%s", "GetValidators:"+err.Error())
	}

	list := make([]string, 0, len(validators))
	for _, v := range validators {
		pub := model.PubKeyFromByte(v.Pubkey)
		list = append(list, pub.SS58())
	}
	return list, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
