package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"

	"github.com/vektah/gqlparser/v2/gqlerror"
	"github.com/wetee-dao/tee-dsecret/pkg/model"
)

// Validators is the resolver for the validators field.
func (r *queryResolver) Validators(ctx context.Context) ([]string, error) {
	validators, _, err := sideChain.GetValidators()
	if err != nil {
		return nil, gqlerror.Errorf("GetValidators:" + err.Error())
	}

	list := make([]string, 0, len(validators))
	for _, v := range validators {
		pub := model.PubKeyFromByte(v.Pubkey)
		list = append(list, pub.SS58())
	}
	return list, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
