package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"

	"github.com/vektah/gqlparser/v2/gqlerror"
)

// ContractCall is the resolver for the contractCall field.
func (r *mutationResolver) ContractCall(ctx context.Context, caller string, contract string, method string, args []string, signatureType int, signature string) (bool, error) {
	callerBytes, err := DecodeCaller(caller)
	if err != nil {
		return false, gqlerror.Errorf("caller: %v", err)
	}
	if err := SubmitContractCall(callerBytes, contract, method, args, uint32(signatureType), signature); err != nil {
		return false, gqlerror.Errorf("SubmitTx: %v", err)
	}
	return true, nil
}

// ContractQuery is the resolver for the contractQuery field.
func (r *queryResolver) ContractQuery(ctx context.Context, caller string, contract string, method string, args []string) (string, error) {
	return ContractQuery(caller, contract, method, args)
}
