package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"
	"encoding/hex"

	"github.com/vektah/gqlparser/v2/gqlerror"
	"github.com/wetee-dao/tee-dsecret/pkg/model"
	"github.com/wetee-dao/tee-dsecret/side-chain/contracts"
)

// SystemContractInit is the resolver for the systemContractInit field.
func (r *mutationResolver) SystemContractInit(ctx context.Context, contract string) (bool, error) {
	txn := model.DBINS.NewTransaction()
	defer txn.Rollback()

	if contracts.IsContractIsInit(txn, "dao") {
		return false, gqlerror.Errorf("contract is inited")
	}

	err := SubmitContractCall(sideChain.GetDKG().DkgPubKey.Byte(), "dao", model.MethodToSelector("Init"), [][]byte{}, 0, []byte{})
	if err != nil {
		return false, gqlerror.Errorf("SystemContractInit DecodeCaller: %v", err)
	}

	return false, gqlerror.Errorf("contract is found")
}

// ContractCall is the resolver for the contractCall field.
func (r *mutationResolver) ContractCall(ctx context.Context, caller string, contract string, method string, args []string, signatureType int, signature string) (bool, error) {
	callerBytes, err := DecodeCaller(caller)
	if err != nil {
		return false, gqlerror.Errorf("ContractCall DecodeCaller: %v", err)
	}

	argsBytes := make([][]byte, len(args))
	for i, arg := range args {
		argBytes, err := hex.DecodeString(arg)
		if err != nil {
			return false, gqlerror.Errorf("ContractCall: decode arg: %v", err)
		}
		argsBytes[i] = argBytes
	}

	sig, err := hex.DecodeString(signature)
	if err != nil {
		return false, gqlerror.Errorf("ContractCall DecodeString sign: %v", err)
	}

	if err := SubmitContractCall(callerBytes, contract, model.MethodToSelector(method), argsBytes, uint32(signatureType), sig); err != nil {
		return false, gqlerror.Errorf("SubmitTx: %v", err)
	}
	return true, nil
}

// ContractQuery is the resolver for the contractDryRun field.
func (r *queryResolver) ContractDryRun(ctx context.Context, caller string, contract string, mut bool, method string, args []string) (string, error) {
	callerBt, err := DecodeCaller(caller)
	if err != nil {
		return "", err
	}

	return ContractDryRun(callerBt, contract, mut, method, args)
}
