package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"
	"encoding/hex"

	"github.com/vektah/gqlparser/v2/gqlerror"
	"github.com/wetee-dao/tee-dsecret/pkg/model"
	"github.com/wetee-dao/tee-dsecret/side-chain/contracts"
)

// SystemContractInit is the resolver for the systemContractInit field.
func (r *mutationResolver) SystemContractInit(ctx context.Context, contract string) (bool, error) {
	txn := model.DBINS.NewTransaction()
	defer txn.Rollback()

	if contracts.IsContractIsInited(txn, "gov") {
		return false, gqlerror.Errorf("contract is inited")
	}

	err := SubmitContractCall(sideChain.GetDKG().DkgPubKey.Byte(), 0, "gov", model.MethodToSelector("Init"), [][]byte{}, []byte{})
	if err != nil {
		return false, gqlerror.Errorf("SystemContractInit DecodeCaller: %v", err)
	}

	return true, nil
}

// ContractCall is the resolver for the contractCall field.
func (r *mutationResolver) ContractCall(ctx context.Context, caller string, callerType int, contract string, method string, args []string, signature string) (bool, error) {
	callerBytes, err := DecodeCaller(caller)
	if err != nil {
		return false, gqlerror.Errorf("ContractCall DecodeCaller: %v", err)
	}

	argBytes, err := decodeArgs(args)
	if err != nil {
		return false, gqlerror.Errorf("ContractCall: %v", err)
	}

	sig, err := hex.DecodeString(signature)
	if err != nil {
		return false, gqlerror.Errorf("ContractCall DecodeString sign: %v", err)
	}

	if err := SubmitContractCall(callerBytes, uint32(callerType), contract, model.MethodToSelector(method), argBytes, sig); err != nil {
		return false, gqlerror.Errorf("SubmitTx: %v", err)
	}
	return true, nil
}

// ContractQuery is the resolver for the contractDryRun field.
func (r *queryResolver) ContractDryRun(ctx context.Context, caller string, callerType int, contract string, mut bool, method string, args []string) (string, error) {
	callerBt, err := DecodeCaller(caller)
	if err != nil {
		return "", err
	}

	argBytes, err := decodeArgs(args)
	if err != nil {
		return "", gqlerror.Errorf("ContractDryRun: %v", err)
	}

	return ContractDryRun(callerBt, callerType, contract, mut, method, argBytes)
}
