// Contractgen 扫描合约包目录，根据 DaoMutation / DaoQuery（可配置）上的导出方法生成 ExecCall / ExecQuery。
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

func main() {
	dir := flag.String("dir", "", "合约包目录（含 .go 源文件，必填）")
	out := flag.String("out", "", "输出文件名，默认 <dir>/dao_gen.go")
	mutation := flag.String("mutation", "DaoMutation", "mutation 接收者类型名")
	query := flag.String("query", "DaoQuery", "query 接收者类型名")
	skipMut := flag.String("skip-mutation", "Delete", "逗号分隔：不生成 dispatch 的 mutation 方法名")
	skipQ := flag.String("skip-query", "", "逗号分隔：不生成 dispatch 的 query 方法名")
	errPrefix := flag.String("err-prefix", "", "错误信息前缀，默认与包名相同")
	execCall := flag.String("exec-call", "ExecCall", "跳过自身：mutation 上的 dispatch 方法名")
	execQuery := flag.String("exec-query", "ExecQuery", "跳过自身：query 上的 dispatch 方法名")
	abiOut := flag.String("abi-out", "", "ink metadata 输出路径；默认 <dir>/../../abis/<包名>.json（contracts/<pkg> 布局时）")
	abiSkip := flag.Bool("abi-skip", false, "不生成 ABI")
	daoStruct := flag.String("dao-struct", "DAO", "DAO 结构体名称，用于生成 NewDAO 构造函数")
	daoSkip := flag.Bool("dao-skip", false, "不生成 NewDAO 构造函数")
	flag.Parse()

	if *dir == "" {
		fmt.Fprintln(os.Stderr, "contractgen: -dir is required")
		os.Exit(1)
	}
	abs, err := filepath.Abs(*dir)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	outPath := *out
	if outPath == "" {
		outPath = filepath.Join(abs, "dao_gen.go")
	}
	outBase := filepath.Base(outPath)

	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, abs, func(fi os.FileInfo) bool {
		if strings.HasSuffix(fi.Name(), "_test.go") {
			return false
		}
		if fi.Name() == outBase {
			return false
		}
		return strings.HasSuffix(fi.Name(), ".go")
	}, parser.ParseComments)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if len(pkgs) != 1 {
		fmt.Fprintf(os.Stderr, "contractgen: expected single package in %s, got %d\n", abs, len(pkgs))
		os.Exit(1)
	}
	var pkg *ast.Package //nolint:staticcheck // parser.ParseDir 返回 map[string]*ast.Package
	for _, p := range pkgs {
		pkg = p
		break
	}
	pkgName := ""
	for _, f := range pkg.Files {
		pkgName = f.Name.Name
		break
	}
	prefix := *errPrefix
	if prefix == "" {
		prefix = pkgName
	}

	skipM := parseSkip(*skipMut)
	skipQset := parseSkip(*skipQ)

	var mutMethods, qMethods []*methodSig
	var daoFields []storeMappingField
	for _, f := range pkg.Files {
		for _, decl := range f.Decls {
			switch d := decl.(type) {
			case *ast.FuncDecl:
				if d.Recv == nil || d.Name == nil {
					continue
				}
				recvName := recvTypeName(d.Recv.List[0].Type)
				if recvName == "" {
					continue
				}
				name := d.Name.Name
				if !ast.IsExported(name) {
					continue
				}
				switch recvName {
				case *mutation:
					if name == *execCall {
						continue
					}
					if skipM[name] {
						continue
					}
					ms, err := parseMethod(d, fset, true)
					if err != nil {
						fmt.Fprintf(os.Stderr, "contractgen %s.%s: %v\n", recvName, name, err)
						os.Exit(1)
					}
					mutMethods = append(mutMethods, ms)
				case *query:
					if name == *execQuery {
						continue
					}
					if skipQset[name] {
						continue
					}
					ms, err := parseMethod(d, fset, false)
					if err != nil {
						fmt.Fprintf(os.Stderr, "contractgen %s.%s: %v\n", recvName, name, err)
						os.Exit(1)
					}
					qMethods = append(qMethods, ms)
				}
			case *ast.GenDecl:
				// 解析 DAO 结构体定义
				if !*daoSkip && d.Tok == token.TYPE {
					for _, spec := range d.Specs {
						ts, ok := spec.(*ast.TypeSpec)
						if !ok || ts.Name == nil || ts.Name.Name != *daoStruct {
							continue
						}
						st, ok := ts.Type.(*ast.StructType)
						if !ok {
							continue
						}
						daoFields = parseDAOFields(st, fset)
					}
				}
			}
		}
	}

	sort.Slice(mutMethods, func(i, j int) bool {
		return mutMethods[i].caseName < mutMethods[j].caseName
	})
	sort.Slice(qMethods, func(i, j int) bool {
		return qMethods[i].caseName < qMethods[j].caseName
	})

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by contractgen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)
	fmt.Fprintf(&buf, "import (\n")
	fmt.Fprintf(&buf, "\t\"errors\"\n")
	fmt.Fprintf(&buf, "\t\"fmt\"\n\n")
	fmt.Fprintf(&buf, "\t\"github.com/centrifuge/go-substrate-rpc-client/v4/types/codec\"\n")
	fmt.Fprintf(&buf, "\t\"github.com/wetee-dao/tee-dsecret/pkg/model\"\n")
	fmt.Fprintf(&buf, ")\n\n")

	writeExecCall(&buf, *mutation, mutMethods, prefix)
	writeExecQuery(&buf, *query, qMethods, prefix)
	if !*daoSkip && len(daoFields) > 0 {
		writeNewDAO(&buf, *daoStruct, pkgName, daoFields)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n%s", err, buf.String())
		os.Exit(1)
	}
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "contractgen: wrote %s\n", outPath)

	abiOutPath := *abiOut
	if abiOutPath == "" {
		// abs 通常为 .../side-chain/contracts/<pkg>，ABI 放在 .../side-chain/abis/<pkg>.json
		abiOutPath = filepath.Join(abs, "..", "..", "abis", pkgName+".json")
	}
	if !*abiSkip {
		if err := writeABI(abiOutPath, pkgName, mutMethods, qMethods); err != nil {
			fmt.Fprintf(os.Stderr, "contractgen abi: %v\n", err)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "contractgen: wrote %s\n", abiOutPath)
	}
}

func parseSkip(s string) map[string]bool {
	m := make(map[string]bool)
	for _, p := range strings.Split(s, ",") {
		p = strings.TrimSpace(p)
		if p != "" {
			m[p] = true
		}
	}
	return m
}

func recvTypeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return recvTypeName(t.X)
	default:
		return ""
	}
}

type methodSig struct {
	goName       string
	caseName     string
	params       []param
	isInit       bool
	queryResult0 string // query 第一个返回值类型字符串，用于生成 ABI returnType
}

type param struct {
	name       string
	typ        string
	underlying string
	isPtr      bool
}

func parseMethod(fd *ast.FuncDecl, fset *token.FileSet, isMutation bool) (*methodSig, error) {
	name := fd.Name.Name
	ms := &methodSig{goName: name, caseName: snakeCase(name)}

	if fd.Type.Params != nil {
		for _, field := range fd.Type.Params.List {
			typStr := typeString(fset, field.Type)
			if len(field.Names) == 0 {
				p := param{name: "", typ: typStr}
				setPtrUnderlying(&p)
				ms.params = append(ms.params, p)
				continue
			}
			for _, id := range field.Names {
				p := param{name: id.Name, typ: typStr}
				setPtrUnderlying(&p)
				ms.params = append(ms.params, p)
			}
		}
	}

	if isMutation {
		if fd.Type.Results == nil || len(fd.Type.Results.List) != 1 {
			return nil, fmt.Errorf("mutation must return a single error")
		}
		rt := typeString(fset, fd.Type.Results.List[0].Type)
		if rt != "error" {
			return nil, fmt.Errorf("mutation must return error, got %s", rt)
		}
		if name == "Init" && len(ms.params) >= 4 {
			last := ms.params[len(ms.params)-1]
			if last.isPtr {
				ms.isInit = true
			}
		}
		return ms, nil
	}

	if fd.Type.Results == nil || len(fd.Type.Results.List) != 2 {
		return nil, fmt.Errorf("query must return (T, error)")
	}
	r1 := typeString(fset, fd.Type.Results.List[1].Type)
	if r1 != "error" {
		return nil, fmt.Errorf("query second result must be error, got %s", r1)
	}
	ms.queryResult0 = typeString(fset, fd.Type.Results.List[0].Type)
	return ms, nil
}

func setPtrUnderlying(p *param) {
	if strings.HasPrefix(p.typ, "*") {
		p.isPtr = true
		p.underlying = strings.TrimPrefix(p.typ, "*")
	} else {
		p.underlying = p.typ
	}
}

func typeString(fset *token.FileSet, expr ast.Expr) string {
	var buf bytes.Buffer
	_ = printer.Fprint(&buf, fset, expr)
	return strings.TrimSpace(buf.String())
}

func snakeCase(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteByte('_')
		}
		b.WriteRune(unicode.ToLower(r))
	}
	return b.String()
}

func writeExecCall(buf *bytes.Buffer, mutation string, methods []*methodSig, prefix string) {
	shortName := strings.TrimPrefix(mutation, "*")
	fmt.Fprintf(buf, "// ExecCall 解析 Tx.contract，再按 Method 与字符串参数列表调用对应变更。\n")
	fmt.Fprintf(buf, "func (d %s) ExecCall(call *model.ContractCall) error {\n", shortName)
	fmt.Fprintf(buf, "\tif len(d.api.GetCaller()) == 0 {\n")
	fmt.Fprintf(buf, "\t\treturn errors.New(%q)\n", prefix+": missing caller")
	fmt.Fprintf(buf, "\t}\n\n")
	fmt.Fprintf(buf, "\tdao := NewDAO(d.api)\n")
	fmt.Fprintf(buf, "\tm := %s{DAO: *dao}\n\n", shortName)
	fmt.Fprintf(buf, "\tmethod := call.Method\n")
	fmt.Fprintf(buf, "\targs := call.Args\n")
	fmt.Fprintf(buf, "\tswitch method {\n")
	for _, m := range methods {
		if m.isInit {
			writeInitCase(buf, m)
			continue
		}
		writeMutationCase(buf, m)
	}
	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn fmt.Errorf(%q, method)\n", prefix+": unknown method %q")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n\n")
}

// Init：与 SCALE 约定一致——至少 3 个参数，第 4 个可选 defaultTrack（TrackData）。
func writeInitCase(buf *bytes.Buffer, m *methodSig) {
	fmt.Fprintf(buf, "\tcase %q:\n", m.caseName)
	fmt.Fprintf(buf, "\t\tif err := model.RequireArgLen(args, 3, method); err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn err\n")
	fmt.Fprintf(buf, "\t\t}\n")
	p0 := m.params[0]
	p1 := m.params[1]
	p2 := m.params[2]
	last := m.params[3]

	fmt.Fprintf(buf, "\t\tmembers, err := model.DecodeScaleArgBytes[%s](args[0])\n", p0.underlying)
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn fmt.Errorf(%q, err)\n", "init: members: %w")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tpub, err := model.DecodeScaleArgBytes[%s](args[1])\n", p1.underlying)
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn fmt.Errorf(%q, err)\n", "init: publicJoin: %w")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\tsudo, err := model.DecodeScaleArgBytes[%s](args[2])\n", p2.underlying)
	fmt.Fprintf(buf, "\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\treturn fmt.Errorf(%q, err)\n", "init: sudoAccount: %w")
	fmt.Fprintf(buf, "\t\t}\n")

	fmt.Fprintf(buf, "\t\tvar dt *%s\n", last.underlying)
	fmt.Fprintf(buf, "\t\tif len(args) >= 4 {\n")
	fmt.Fprintf(buf, "\t\t\tt, err := model.DecodeScaleArgBytes[%s](args[3])\n", last.underlying)
	fmt.Fprintf(buf, "\t\t\tif err != nil {\n")
	fmt.Fprintf(buf, "\t\t\t\treturn fmt.Errorf(%q, err)\n", "init: defaultTrack: %w")
	fmt.Fprintf(buf, "\t\t\t}\n")
	fmt.Fprintf(buf, "\t\t\tdt = &t\n")
	fmt.Fprintf(buf, "\t\t}\n")
	fmt.Fprintf(buf, "\t\treturn m.Init(members, pub, sudo, dt)\n")
}

func writeMutationCase(buf *bytes.Buffer, m *methodSig) {
	fmt.Fprintf(buf, "\tcase %q:\n", m.caseName)
	if len(m.params) == 0 {
		fmt.Fprintf(buf, "\t\treturn m.%s()\n", m.goName)
		return
	}

	fmt.Fprintf(buf, "\t\tif err := model.RequireArgLen(args, %d, method); err != nil {\n", len(m.params))
	fmt.Fprintf(buf, "\t\t\treturn err\n")
	fmt.Fprintf(buf, "\t\t}\n")

	var argNames []string
	for i := range m.params {
		p := m.params[i]
		dec := localName(p.name, i, "a")
		fmt.Fprintf(buf, "\t\t%s, err := model.DecodeScaleArgBytes[%s](args[%d])\n", dec, p.underlying, i)
		errKey := errLabel(m, p, i)
		if shortDecodeErr(m.goName, len(m.params)) {
			fmt.Fprintf(buf, "\t\tif err != nil {\n")
			fmt.Fprintf(buf, "\t\t\treturn fmt.Errorf(%q, err)\n", m.caseName+": %w")
			fmt.Fprintf(buf, "\t\t}\n")
		} else {
			fmt.Fprintf(buf, "\t\tif err != nil {\n")
			fmt.Fprintf(buf, "\t\t\treturn fmt.Errorf(%q, err)\n", m.caseName+": "+errKey+": %w")
			fmt.Fprintf(buf, "\t\t}\n")
		}

		if p.isPtr {
			ptr := dec + "p"
			fmt.Fprintf(buf, "\t\t%s := &%s\n", ptr, dec)
			argNames = append(argNames, ptr)
		} else {
			argNames = append(argNames, dec)
		}
	}

	fmt.Fprintf(buf, "\t\treturn m.%s(%s)\n", m.goName, strings.Join(argNames, ", "))
}

func shortDecodeErr(goName string, n int) bool {
	if n != 1 {
		return false
	}
	return goName == "SetPublicJoin" || goName == "AddTrack"
}

func errLabel(m *methodSig, p param, idx int) string {
	if p.name != "" {
		return p.name
	}
	return fmt.Sprintf("arg%d", idx)
}

func localName(paramName string, idx int, prefix string) string {
	if paramName == "" {
		return fmt.Sprintf("%s%d", prefix, idx)
	}
	return paramName
}

func writeExecQuery(buf *bytes.Buffer, query string, methods []*methodSig, prefix string) {
	shortName := strings.TrimPrefix(query, "*")
	fmt.Fprintf(buf, "// ExecuteQuery 按 method 将字符串参数解析为合约查询实参，返回 SCALE 编码结果。\n")
	fmt.Fprintf(buf, "func (q %s) ExecQuery(call *model.ContractCall) ([]byte, error) {\n", shortName)
	fmt.Fprintf(buf, "\tif call.Method == \"\" {\n")
	fmt.Fprintf(buf, "\t\treturn nil, errors.New(%q)\n", prefix+": empty query method")
	fmt.Fprintf(buf, "\t}\n\n")
	fmt.Fprintf(buf, "\targs := call.Args\n")
	fmt.Fprintf(buf, "\tmethod := call.Method\n\n")
	fmt.Fprintf(buf, "\tswitch method {\n")

	for _, m := range methods {
		fmt.Fprintf(buf, "\tcase %q:\n", m.caseName)
		if len(m.params) == 0 {
			fmt.Fprintf(buf, "\t\tout, err := q.%s()\n", m.goName)
			fmt.Fprintf(buf, "\t\tif err != nil {\n")
			fmt.Fprintf(buf, "\t\t\treturn nil, err\n")
			fmt.Fprintf(buf, "\t\t}\n")
			fmt.Fprintf(buf, "\t\treturn codec.Encode(out)\n")
			continue
		}

		fmt.Fprintf(buf, "\t\tif err := model.RequireArgLen(args, %d, method); err != nil {\n", len(m.params))
		fmt.Fprintf(buf, "\t\t\treturn nil, err\n")
		fmt.Fprintf(buf, "\t\t}\n")

		var argNames []string
		for i := range m.params {
			p := m.params[i]
			dec := localName(p.name, i, "a")
			fmt.Fprintf(buf, "\t\t%s, err := model.DecodeScaleArgBytes[%s](args[%d])\n", dec, p.underlying, i)
			errKey := errLabel(m, p, i)
			fmt.Fprintf(buf, "\t\tif err != nil {\n")
			fmt.Fprintf(buf, "\t\t\treturn nil, fmt.Errorf(%q, err)\n", m.caseName+": "+errKey+": %w")
			fmt.Fprintf(buf, "\t\t}\n")
			if p.isPtr {
				ptr := dec + "p"
				fmt.Fprintf(buf, "\t\t%s := &%s\n", ptr, dec)
				argNames = append(argNames, ptr)
			} else {
				argNames = append(argNames, dec)
			}
		}

		fmt.Fprintf(buf, "\t\tout, err := q.%s(%s)\n", m.goName, strings.Join(argNames, ", "))
		fmt.Fprintf(buf, "\t\tif err != nil {\n")
		fmt.Fprintf(buf, "\t\t\treturn nil, err\n")
		fmt.Fprintf(buf, "\t\t}\n")
		fmt.Fprintf(buf, "\t\treturn codec.Encode(out)\n")
	}

	fmt.Fprintf(buf, "\tdefault:\n")
	fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(%q, method)\n", prefix+": unknown query method %q")
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n")
}

// storeMappingField 表示 DAO 结构体中的一个 StoreMapping 字段
type storeMappingField struct {
	name    string // 字段名
	keyType string // StoreMapping 的 Key 类型
	valType string // StoreMapping 的 Value 类型
	keyPfx  string // KeyPrefix
}

// parseDAOFields 解析 DAO 结构体中的 StoreMapping 字段
func parseDAOFields(st *ast.StructType, fset *token.FileSet) []storeMappingField {
	var fields []storeMappingField
	if st.Fields == nil {
		return fields
	}
	for _, field := range st.Fields.List {
		if len(field.Names) == 0 {
			continue
		}
		fieldName := field.Names[0].Name
		typStr := typeString(fset, field.Type)
		keyType, valType, ok := parseStoreMappingType(typStr)
		if !ok {
			continue
		}
		// 检查注释中是否有自定义 KeyPrefix
		// 格式: `store:"keyPfx:xxx"` 或 `//keyPfx:xxx`
		keyPfx := ""
		// 先检查行尾注释（Comment）
		if field.Comment != nil {
			for _, c := range field.Comment.List {
				text := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
				if strings.HasPrefix(text, "keyPfx:") {
					keyPfx = strings.TrimSpace(strings.TrimPrefix(text, "keyPfx:"))
					break
				}
			}
		}
		// 再检查文档注释（Doc）
		if keyPfx == "" && field.Doc != nil {
			for _, c := range field.Doc.List {
				text := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
				if strings.HasPrefix(text, "keyPfx:") {
					keyPfx = strings.TrimSpace(strings.TrimPrefix(text, "keyPfx:"))
					break
				}
			}
		}
		if keyPfx == "" && field.Tag != nil {
			// 解析 struct tag: `store:"keyPfx:xxx"`
			tag := strings.Trim(field.Tag.Value, "`")
			if storeTag, ok := reflectParseStructTag(tag, "store"); ok {
				if pfx, ok := storeTag["keyPfx"]; ok {
					keyPfx = pfx
				}
			}
		}
		if keyPfx == "" {
			keyPfx = storeKeyPrefix(fieldName)
		}
		fields = append(fields, storeMappingField{
			name:    fieldName,
			keyType: keyType,
			valType: valType,
			keyPfx:  keyPfx,
		})
	}
	return fields
}

// reflectParseStructTag 简单解析 struct tag
func reflectParseStructTag(tag, key string) (map[string]string, bool) {
	// 查找 key:"value" 格式
	idx := strings.Index(tag, key+`:`)
	if idx == -1 {
		return nil, false
	}
	start := idx + len(key) + 2 // 跳过 key:"
	end := strings.Index(tag[start:], `"`)
	if end == -1 {
		return nil, false
	}
	value := tag[start : start+end]
	// 解析 key1:val1,key2:val2 格式
	result := make(map[string]string)
	for _, pair := range strings.Split(value, ",") {
		parts := strings.SplitN(pair, ":", 2)
		if len(parts) == 2 {
			result[parts[0]] = parts[1]
		}
	}
	return result, true
}

// parseStoreMappingType 解析 *model.StoreMapping[K, V] 类型，返回 K, V 类型字符串
func parseStoreMappingType(typ string) (key, val string, ok bool) {
	// 匹配 *model.StoreMapping[K, V] 或 model.StoreMapping[K, V]
	typ = strings.TrimSpace(typ)
	if strings.HasPrefix(typ, "*") {
		typ = typ[1:]
	}
	if !strings.HasPrefix(typ, "model.StoreMapping[") || !strings.HasSuffix(typ, "]") {
		return "", "", false
	}
	inner := typ[len("model.StoreMapping[") : len(typ)-1]
	// 解析 [K, V] 中的 K 和 V，需要处理嵌套的 [] 和 ,
	k, v, ok := parseTypePair(inner)
	if !ok {
		return "", "", false
	}
	return k, v, true
}

// parseTypePair 解析 "K, V" 格式的类型对，处理嵌套的 [] 和 ,
func parseTypePair(s string) (k, v string, ok bool) {
	s = strings.TrimSpace(s)
	depth := 0
	for i, c := range s {
		switch c {
		case '[', '(':
			depth++
		case ']', ')':
			depth--
		case ',':
			if depth == 0 {
				k = strings.TrimSpace(s[:i])
				v = strings.TrimSpace(s[i+1:])
				return k, v, true
			}
		}
	}
	return "", "", false
}

// storeKeyPrefix 根据字段名生成 KeyPrefix
// 规则：驼峰转蛇形，处理复数形式（去掉末尾 s），去掉特定后缀（Store），加下划线
func storeKeyPrefix(field string) string {
	// 去掉特定后缀
	name := strings.TrimSuffix(field, "Store")
	// 转蛇形（处理连续大写字母如 ID）
	snake := smartSnakeCase(name)
	// 处理复数形式（简单去掉末尾 s）
	if strings.HasSuffix(snake, "s") && !strings.HasSuffix(snake, "ss") {
		snake = snake[:len(snake)-1]
	}
	return snake + "_"
}

// smartSnakeCase 将驼峰转为蛇形，处理连续大写字母（如 ID -> id）
func smartSnakeCase(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			// 前一个字符是小写，或者后一个字符是小写，才添加下划线
			// 连续大写字母不添加下划线（如 ID）
			prev := []rune(s)[i-1]
			if prev >= 'a' && prev <= 'z' {
				b.WriteByte('_')
			} else if i+1 < len(s) {
				next := []rune(s)[i+1]
				if next >= 'a' && next <= 'z' {
					b.WriteByte('_')
				}
			}
		}
		b.WriteRune(unicode.ToLower(r))
	}
	return b.String()
}

// writeNewDAO 生成 NewDAO 构造函数
func writeNewDAO(buf *bytes.Buffer, daoName, pkgName string, fields []storeMappingField) {
	fmt.Fprintf(buf, "\nfunc NewDAO(api model.ContractApi) *%s {\n", daoName)
	fmt.Fprintf(buf, "\treturn &%s{\n", daoName)
	fmt.Fprintf(buf, "\t\tapi: api,\n")
	for _, f := range fields {
		fmt.Fprintf(buf, "\t\t%s: &model.StoreMapping[%s, %s]{Namespace: %q, KeyPrefix: %q},\n",
			f.name, f.keyType, f.valType, pkgName, f.keyPfx)
	}
	fmt.Fprintf(buf, "\t}\n")
	fmt.Fprintf(buf, "}\n")
}
