apiVersion: apps/v1
kind: Deployment
metadata:
  name: $NAME
  namespace: worker-addon
spec:
  selector:
    matchLabels:
      app: $NAME
  template:
    metadata:
      labels:
        app: $NAME
    spec:
      containers:
        - name: c0
          image: $DSECRET_IMAGE
          ports:
            - containerPort: $SIDE_CHAIN_PORT
              name: side
              protocol: TCP
            - containerPort: $GQL_PORT
              name: qgl
              protocol: TCP
          env:
            - name: SIDE_CHAIN_PORT
              value: '$SIDE_CHAIN_PORT'
            - name: GQL_PORT
              value: '$GQL_PORT'
            - name: CHAIN_ADDR
              value: $CHAIN_ADDR
          volumeMounts:
            - name: $NAME
              mountPath: /chain_data
          resources:
            limits:
              alibabacloud.com/sgx_epc_MiB: 10
            requests:
              alibabacloud.com/sgx_epc_MiB: 10
      volumes:
        - name: $NAME
          hostPath:
            type: DirectoryOrCreate
            path: $DSECRET_DIR
      nodeSelector:
        TEE: "SGX"

---
apiVersion: v1
kind: Service
metadata:
  name: $NAME-service
  namespace: worker-addon
spec:
  type: NodePort
  selector:
    app: $NAME
  ports:
    - name: side
      protocol: TCP
      nodePort: $SIDE_CHAIN_PORT
      port: $SIDE_CHAIN_PORT
      targetPort: $SIDE_CHAIN_PORT
    - name: qgl
      protocol: TCP
      nodePort: $GQL_PORT
      port: $GQL_PORT
      targetPort: $GQL_PORT
