// Code generated by contractgen; DO NOT EDIT.

package dao

import (
	"errors"
	"fmt"

	"github.com/centrifuge/go-substrate-rpc-client/v4/types/codec"
	"github.com/wetee-dao/tee-dsecret/pkg/model"
)

// ExecCall 解析 Tx.contract，再按 Method 与字符串参数列表调用对应变更。
func (d DaoMutation) ExecCall(call *model.ContractCall) error {
	if len(d.api.GetCaller()) == 0 {
		return errors.New("dao: missing caller")
	}

	dao := NewDAO(d.api)
	m := DaoMutation{DAO: *dao}

	method := call.Method
	args := call.Args
	switch method {
	case "add_track":
		if err := model.RequireArgLen(args, 1, method); err != nil {
			return err
		}
		track, err := model.DecodeScaleArgBytes[TrackData](args[0])
		if err != nil {
			return fmt.Errorf("add_track: %w", err)
		}
		return m.AddTrack(track)
	case "approve":
		if err := model.RequireArgLen(args, 2, method); err != nil {
			return err
		}
		spender, err := model.DecodeScaleArgBytes[[]byte](args[0])
		if err != nil {
			return fmt.Errorf("approve: spender: %w", err)
		}
		value, err := model.DecodeScaleArgBytes[[]byte](args[1])
		if err != nil {
			return fmt.Errorf("approve: value: %w", err)
		}
		return m.Approve(spender, value)
	case "cancel_proposal":
		if err := model.RequireArgLen(args, 1, method); err != nil {
			return err
		}
		proposalID, err := model.DecodeScaleArgBytes[uint32](args[0])
		if err != nil {
			return fmt.Errorf("cancel_proposal: proposalID: %w", err)
		}
		return m.CancelProposal(proposalID)
	case "cancel_vote":
		if err := model.RequireArgLen(args, 1, method); err != nil {
			return err
		}
		voteID, err := model.DecodeScaleArgBytes[uint64](args[0])
		if err != nil {
			return fmt.Errorf("cancel_vote: voteID: %w", err)
		}
		return m.CancelVote(voteID)
	case "deposit_proposal":
		if err := model.RequireArgLen(args, 2, method); err != nil {
			return err
		}
		proposalID, err := model.DecodeScaleArgBytes[uint32](args[0])
		if err != nil {
			return fmt.Errorf("deposit_proposal: proposalID: %w", err)
		}
		amount, err := model.DecodeScaleArgBytes[[]byte](args[1])
		if err != nil {
			return fmt.Errorf("deposit_proposal: amount: %w", err)
		}
		return m.DepositProposal(proposalID, amount)
	case "exec_proposal":
		if err := model.RequireArgLen(args, 1, method); err != nil {
			return err
		}
		proposalID, err := model.DecodeScaleArgBytes[uint32](args[0])
		if err != nil {
			return fmt.Errorf("exec_proposal: proposalID: %w", err)
		}
		return m.ExecProposal(proposalID)
	case "init":
		if err := model.RequireArgLen(args, 3, method); err != nil {
			return err
		}
		members, err := model.DecodeScaleArgBytes[[]Member](args[0])
		if err != nil {
			return fmt.Errorf("init: members: %w", err)
		}
		pub, err := model.DecodeScaleArgBytes[bool](args[1])
		if err != nil {
			return fmt.Errorf("init: publicJoin: %w", err)
		}
		sudo, err := model.DecodeScaleArgBytes[[]byte](args[2])
		if err != nil {
			return fmt.Errorf("init: sudoAccount: %w", err)
		}
		var dt *TrackData
		if len(args) >= 4 {
			t, err := model.DecodeScaleArgBytes[TrackData](args[3])
			if err != nil {
				return fmt.Errorf("init: defaultTrack: %w", err)
			}
			dt = &t
		}
		return m.Init(members, pub, sudo, dt)
	case "join":
		if err := model.RequireArgLen(args, 2, method); err != nil {
			return err
		}
		newUser, err := model.DecodeScaleArgBytes[[]byte](args[0])
		if err != nil {
			return fmt.Errorf("join: newUser: %w", err)
		}
		balance, err := model.DecodeScaleArgBytes[[]byte](args[1])
		if err != nil {
			return fmt.Errorf("join: balance: %w", err)
		}
		return m.Join(newUser, balance)
	case "leave":
		return m.Leave()
	case "leave_with_burn":
		return m.LeaveWithBurn()
	case "payout":
		if err := model.RequireArgLen(args, 1, method); err != nil {
			return err
		}
		spendID, err := model.DecodeScaleArgBytes[uint64](args[0])
		if err != nil {
			return fmt.Errorf("payout: spendID: %w", err)
		}
		return m.Payout(spendID)
	case "public_join":
		return m.PublicJoin()
	case "set_default_track":
		if err := model.RequireArgLen(args, 1, method); err != nil {
			return err
		}
		trackID, err := model.DecodeScaleArgBytes[uint32](args[0])
		if err != nil {
			return fmt.Errorf("set_default_track: trackID: %w", err)
		}
		return m.SetDefaultTrack(trackID)
	case "set_public_join":
		if err := model.RequireArgLen(args, 1, method); err != nil {
			return err
		}
		publicJoin, err := model.DecodeScaleArgBytes[bool](args[0])
		if err != nil {
			return fmt.Errorf("set_public_join: %w", err)
		}
		return m.SetPublicJoin(publicJoin)
	case "spend":
		if err := model.RequireArgLen(args, 3, method); err != nil {
			return err
		}
		to, err := model.DecodeScaleArgBytes[[]byte](args[0])
		if err != nil {
			return fmt.Errorf("spend: to: %w", err)
		}
		amount, err := model.DecodeScaleArgBytes[[]byte](args[1])
		if err != nil {
			return fmt.Errorf("spend: amount: %w", err)
		}
		trackID, err := model.DecodeScaleArgBytes[uint32](args[2])
		if err != nil {
			return fmt.Errorf("spend: trackID: %w", err)
		}
		return m.Spend(to, amount, trackID)
	case "submit_proposal":
		if err := model.RequireArgLen(args, 2, method); err != nil {
			return err
		}
		call, err := model.DecodeScaleArgBytes[CallContent](args[0])
		if err != nil {
			return fmt.Errorf("submit_proposal: call: %w", err)
		}
		trackID, err := model.DecodeScaleArgBytes[uint32](args[1])
		if err != nil {
			return fmt.Errorf("submit_proposal: trackID: %w", err)
		}
		return m.SubmitProposal(call, trackID)
	case "submit_vote":
		if err := model.RequireArgLen(args, 3, method); err != nil {
			return err
		}
		proposalID, err := model.DecodeScaleArgBytes[uint32](args[0])
		if err != nil {
			return fmt.Errorf("submit_vote: proposalID: %w", err)
		}
		opinionYes, err := model.DecodeScaleArgBytes[bool](args[1])
		if err != nil {
			return fmt.Errorf("submit_vote: opinionYes: %w", err)
		}
		lockAmount, err := model.DecodeScaleArgBytes[[]byte](args[2])
		if err != nil {
			return fmt.Errorf("submit_vote: lockAmount: %w", err)
		}
		return m.SubmitVote(proposalID, opinionYes, lockAmount)
	case "transfer":
		if err := model.RequireArgLen(args, 2, method); err != nil {
			return err
		}
		to, err := model.DecodeScaleArgBytes[[]byte](args[0])
		if err != nil {
			return fmt.Errorf("transfer: to: %w", err)
		}
		value, err := model.DecodeScaleArgBytes[[]byte](args[1])
		if err != nil {
			return fmt.Errorf("transfer: value: %w", err)
		}
		return m.Transfer(to, value)
	case "transfer_from":
		if err := model.RequireArgLen(args, 3, method); err != nil {
			return err
		}
		from, err := model.DecodeScaleArgBytes[[]byte](args[0])
		if err != nil {
			return fmt.Errorf("transfer_from: from: %w", err)
		}
		to, err := model.DecodeScaleArgBytes[[]byte](args[1])
		if err != nil {
			return fmt.Errorf("transfer_from: to: %w", err)
		}
		value, err := model.DecodeScaleArgBytes[[]byte](args[2])
		if err != nil {
			return fmt.Errorf("transfer_from: value: %w", err)
		}
		return m.TransferFrom(from, to, value)
	case "unlock":
		if err := model.RequireArgLen(args, 1, method); err != nil {
			return err
		}
		voteID, err := model.DecodeScaleArgBytes[uint64](args[0])
		if err != nil {
			return fmt.Errorf("unlock: voteID: %w", err)
		}
		return m.Unlock(voteID)
	default:
		return fmt.Errorf("dao: unknown method %q", method)
	}
}

// ExecuteQuery 按 method 将字符串参数解析为合约查询实参，返回 SCALE 编码结果。
func (q DaoQuery) ExecQuery(call *model.ContractCall) ([]byte, error) {
	if call.Method == "" {
		return nil, errors.New("dao: empty query method")
	}

	args := call.Args
	method := call.Method

	switch method {
	case "allowance":
		if err := model.RequireArgLen(args, 2, method); err != nil {
			return nil, err
		}
		owner, err := model.DecodeScaleArgBytes[[]byte](args[0])
		if err != nil {
			return nil, fmt.Errorf("allowance: owner: %w", err)
		}
		spender, err := model.DecodeScaleArgBytes[[]byte](args[1])
		if err != nil {
			return nil, fmt.Errorf("allowance: spender: %w", err)
		}
		out, err := q.Allowance(owner, spender)
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case "balance_of":
		if err := model.RequireArgLen(args, 1, method); err != nil {
			return nil, err
		}
		owner, err := model.DecodeScaleArgBytes[[]byte](args[0])
		if err != nil {
			return nil, fmt.Errorf("balance_of: owner: %w", err)
		}
		out, err := q.BalanceOf(owner)
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case "default_track":
		out, err := q.DefaultTrack()
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case "lock_balance_of":
		if err := model.RequireArgLen(args, 1, method); err != nil {
			return nil, err
		}
		owner, err := model.DecodeScaleArgBytes[[]byte](args[0])
		if err != nil {
			return nil, fmt.Errorf("lock_balance_of: owner: %w", err)
		}
		out, err := q.LockBalanceOf(owner)
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case "members":
		out, err := q.Members()
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case "proposal":
		if err := model.RequireArgLen(args, 1, method); err != nil {
			return nil, err
		}
		id, err := model.DecodeScaleArgBytes[uint32](args[0])
		if err != nil {
			return nil, fmt.Errorf("proposal: id: %w", err)
		}
		out, err := q.Proposal(id)
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case "proposal_status":
		if err := model.RequireArgLen(args, 1, method); err != nil {
			return nil, err
		}
		id, err := model.DecodeScaleArgBytes[uint32](args[0])
		if err != nil {
			return nil, fmt.Errorf("proposal_status: id: %w", err)
		}
		out, err := q.ProposalStatus(id)
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case "proposals":
		out, err := q.Proposals()
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case "public_join":
		out, err := q.PublicJoin()
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case "total_supply":
		out, err := q.TotalSupply()
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case "track":
		if err := model.RequireArgLen(args, 1, method); err != nil {
			return nil, err
		}
		id, err := model.DecodeScaleArgBytes[uint32](args[0])
		if err != nil {
			return nil, fmt.Errorf("track: id: %w", err)
		}
		out, err := q.Track(id)
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case "tracks":
		out, err := q.Tracks()
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case "vote":
		if err := model.RequireArgLen(args, 1, method); err != nil {
			return nil, err
		}
		id, err := model.DecodeScaleArgBytes[uint64](args[0])
		if err != nil {
			return nil, fmt.Errorf("vote: id: %w", err)
		}
		out, err := q.Vote(id)
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case "votes":
		out, err := q.Votes()
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	default:
		return nil, fmt.Errorf("dao: unknown query method %q", method)
	}
}
