// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

type Mutation struct {
}

type Query struct {
}

type SecretEnv struct {
	Project  string `json:"project"`
	Contract string `json:"contract"`
	CodeHash string `json:"code_hash"`
	Abi      string `json:"abi"`
}
