// Code generated by tools/stategen. DO NOT EDIT.
// 标量：xxx.Members() / xxx.SetMembers(v)；StoreMapping 通过 DaoStorage 按 key 存取。

package dao

import (
	"math/big"

	"strconv"

	"github.com/wetee-dao/tee-dsecret/pkg/model"
)

const stateKeydaoStateTracks = "track_"

const stateKeydaoStateProposals = "proposal_"

const stateKeydaoStateProposalStatus = "proposal_status_"

const stateKeydaoStateProposalTrack = "proposal_track_"

const stateKeydaoStateProposalCaller = "proposal_caller_"

const stateKeydaoStateSubmitBlock = "submit_block_"

const stateKeydaoStateDeposits = "deposit_"

const stateKeydaoStateVotes = "vote_"

const stateKeydaoStateVoteOfMember = "vote_of_member_"

const stateKeydaoStateUnlock = "unlock_"

const stateKeydaoStateSpends = "spend_"

const stateKeydaoStateMemberBalance = "member_balance_"

const stateKeydaoStateMemberLock = "member_lock_"

const stateKeydaoStateAllowance = "allowance_"

// daoStateState 按字段读写的 state 访问器，标量用 Methods，mapping 用 state.Tracks.Get(txn, id) 等。
type daoStateState struct {
	txn *model.Txn
	Tracks *model.StoreMapping[uint32]
	Proposals *model.StoreMapping[uint32]
	ProposalStatus *model.StoreMapping[uint32]
	ProposalTrack *model.StoreMapping[uint32]
	ProposalCaller *model.StoreMapping[uint32]
	SubmitBlock *model.StoreMapping[uint32]
	Deposits *model.StoreMapping[uint32]
	Votes *model.StoreMapping[uint64]
	VoteOfMember *model.StoreMapping[[]byte]
	Unlock *model.StoreMapping[uint64]
	Spends *model.StoreMapping[uint64]
	MemberBalance *model.StoreMapping[[]byte]
	MemberLock *model.StoreMapping[[]byte]
	Allowance *model.StoreMapping[string]
}

// newDaoStateState 返回访问器，用法: state := newDaoStateState(txn); state.Members(); state.Tracks.Get(txn, id)
func newDaoStateState(txn *model.Txn) *daoStateState {
	s := &daoStateState{txn: txn}
	s.Tracks = &model.StoreMapping[uint32]{Namespace: "dao", KeyPrefix: stateKeydaoStateTracks}
	s.Proposals = &model.StoreMapping[uint32]{Namespace: "dao", KeyPrefix: stateKeydaoStateProposals}
	s.ProposalStatus = &model.StoreMapping[uint32]{Namespace: "dao", KeyPrefix: stateKeydaoStateProposalStatus}
	s.ProposalTrack = &model.StoreMapping[uint32]{Namespace: "dao", KeyPrefix: stateKeydaoStateProposalTrack}
	s.ProposalCaller = &model.StoreMapping[uint32]{Namespace: "dao", KeyPrefix: stateKeydaoStateProposalCaller}
	s.SubmitBlock = &model.StoreMapping[uint32]{Namespace: "dao", KeyPrefix: stateKeydaoStateSubmitBlock}
	s.Deposits = &model.StoreMapping[uint32]{Namespace: "dao", KeyPrefix: stateKeydaoStateDeposits}
	s.Votes = &model.StoreMapping[uint64]{Namespace: "dao", KeyPrefix: stateKeydaoStateVotes}
	s.VoteOfMember = &model.StoreMapping[[]byte]{Namespace: "dao", KeyPrefix: stateKeydaoStateVoteOfMember}
	s.Unlock = &model.StoreMapping[uint64]{Namespace: "dao", KeyPrefix: stateKeydaoStateUnlock}
	s.Spends = &model.StoreMapping[uint64]{Namespace: "dao", KeyPrefix: stateKeydaoStateSpends}
	s.MemberBalance = &model.StoreMapping[[]byte]{Namespace: "dao", KeyPrefix: stateKeydaoStateMemberBalance}
	s.MemberLock = &model.StoreMapping[[]byte]{Namespace: "dao", KeyPrefix: stateKeydaoStateMemberLock}
	s.Allowance = &model.StoreMapping[string]{Namespace: "dao", KeyPrefix: stateKeydaoStateAllowance}
	return s
}

const stateKeydaoStateMembers = "state_members"

func (s *daoStateState) Members() [][]byte {
	v, _ := model.TxnGetJson[[][]byte](s.txn, model.ComboNamespaceKey("dao", stateKeydaoStateMembers))
	if v == nil { var z [][]byte; return z }
	return *v
}

func (s *daoStateState) SetMembers(v [][]byte) error {
	return model.TxnSetJson(s.txn, model.ComboNamespaceKey("dao", stateKeydaoStateMembers), &v)
}

const stateKeydaoStateTotalIssuance = "state_total_issuance"

func (s *daoStateState) TotalIssuance() *big.Int {
	b, _ := s.txn.Get(model.ComboNamespaceKey("dao", stateKeydaoStateTotalIssuance))
	return model.BytesToU128(b)
}

func (s *daoStateState) SetTotalIssuance(v *big.Int) error {
	if v == nil { v = big.NewInt(0) }
	return s.txn.SetKey("dao", stateKeydaoStateTotalIssuance, model.U128ToBytes(v))
}

const stateKeydaoStatePublicJoin = "state_public_join"

func (s *daoStateState) PublicJoin() bool {
	b, _ := s.txn.Get(model.ComboNamespaceKey("dao", stateKeydaoStatePublicJoin))
	v, _ := strconv.ParseBool(string(b))
	return v
}

func (s *daoStateState) SetPublicJoin(v bool) error {
	var b []byte
	switch x := any(v).(type) {
	case string:
		b = []byte(x)
	case bool:
		b = []byte(strconv.FormatBool(x))
	case uint32:
		b = []byte(strconv.FormatUint(uint64(x), 10))
	case uint64:
		b = []byte(strconv.FormatUint(x, 10))
	case int64:
		b = []byte(strconv.FormatInt(x, 10))
	case []byte:
		b = x
	default:
		return nil
	}
	return s.txn.SetKey("dao", stateKeydaoStatePublicJoin, b)
}

const stateKeydaoStateSudoAccount = "state_sudo_account"

func (s *daoStateState) SudoAccount() []byte {
	v, _ := model.TxnGetJson[[]byte](s.txn, model.ComboNamespaceKey("dao", stateKeydaoStateSudoAccount))
	if v == nil { var z []byte; return z }
	return *v
}

func (s *daoStateState) SetSudoAccount(v []byte) error {
	return model.TxnSetJson(s.txn, model.ComboNamespaceKey("dao", stateKeydaoStateSudoAccount), &v)
}

const stateKeydaoStateTransfer = "state_transfer"

func (s *daoStateState) Transfer() bool {
	b, _ := s.txn.Get(model.ComboNamespaceKey("dao", stateKeydaoStateTransfer))
	v, _ := strconv.ParseBool(string(b))
	return v
}

func (s *daoStateState) SetTransfer(v bool) error {
	var b []byte
	switch x := any(v).(type) {
	case string:
		b = []byte(x)
	case bool:
		b = []byte(strconv.FormatBool(x))
	case uint32:
		b = []byte(strconv.FormatUint(uint64(x), 10))
	case uint64:
		b = []byte(strconv.FormatUint(x, 10))
	case int64:
		b = []byte(strconv.FormatInt(x, 10))
	case []byte:
		b = x
	default:
		return nil
	}
	return s.txn.SetKey("dao", stateKeydaoStateTransfer, b)
}

const stateKeydaoStateDefaultTrack = "state_default_track"

func (s *daoStateState) DefaultTrack() *uint32 {
	v, _ := model.TxnGetJson[uint32](s.txn, model.ComboNamespaceKey("dao", stateKeydaoStateDefaultTrack))
	return v
}

func (s *daoStateState) SetDefaultTrack(v *uint32) error {
	return model.TxnSetJson(s.txn, model.ComboNamespaceKey("dao", stateKeydaoStateDefaultTrack), v)
}

const stateKeydaoStateNextProposalId = "state_next_proposal_id"

func (s *daoStateState) NextProposalId() uint32 {
	b, _ := s.txn.Get(model.ComboNamespaceKey("dao", stateKeydaoStateNextProposalId))
	v, _ := strconv.ParseUint(string(b), 10, 32)
	return uint32(v)
}

func (s *daoStateState) SetNextProposalId(v uint32) error {
	var b []byte
	switch x := any(v).(type) {
	case string:
		b = []byte(x)
	case bool:
		b = []byte(strconv.FormatBool(x))
	case uint32:
		b = []byte(strconv.FormatUint(uint64(x), 10))
	case uint64:
		b = []byte(strconv.FormatUint(x, 10))
	case int64:
		b = []byte(strconv.FormatInt(x, 10))
	case []byte:
		b = x
	default:
		return nil
	}
	return s.txn.SetKey("dao", stateKeydaoStateNextProposalId, b)
}

const stateKeydaoStateNextVoteId = "state_next_vote_id"

func (s *daoStateState) NextVoteId() uint64 {
	b, _ := s.txn.Get(model.ComboNamespaceKey("dao", stateKeydaoStateNextVoteId))
	v, _ := strconv.ParseUint(string(b), 10, 64)
	return v
}

func (s *daoStateState) SetNextVoteId(v uint64) error {
	var b []byte
	switch x := any(v).(type) {
	case string:
		b = []byte(x)
	case bool:
		b = []byte(strconv.FormatBool(x))
	case uint32:
		b = []byte(strconv.FormatUint(uint64(x), 10))
	case uint64:
		b = []byte(strconv.FormatUint(x, 10))
	case int64:
		b = []byte(strconv.FormatInt(x, 10))
	case []byte:
		b = x
	default:
		return nil
	}
	return s.txn.SetKey("dao", stateKeydaoStateNextVoteId, b)
}

const stateKeydaoStateNextSpendId = "state_next_spend_id"

func (s *daoStateState) NextSpendId() uint64 {
	b, _ := s.txn.Get(model.ComboNamespaceKey("dao", stateKeydaoStateNextSpendId))
	v, _ := strconv.ParseUint(string(b), 10, 64)
	return v
}

func (s *daoStateState) SetNextSpendId(v uint64) error {
	var b []byte
	switch x := any(v).(type) {
	case string:
		b = []byte(x)
	case bool:
		b = []byte(strconv.FormatBool(x))
	case uint32:
		b = []byte(strconv.FormatUint(uint64(x), 10))
	case uint64:
		b = []byte(strconv.FormatUint(x, 10))
	case int64:
		b = []byte(strconv.FormatInt(x, 10))
	case []byte:
		b = x
	default:
		return nil
	}
	return s.txn.SetKey("dao", stateKeydaoStateNextSpendId, b)
}

