// Code generated by contractgen; DO NOT EDIT.

package gov

import (
	"fmt"

	"github.com/centrifuge/go-substrate-rpc-client/v4/types/codec"
	"github.com/wetee-dao/tee-dsecret/pkg/model"
)

// ExecCall 解析 Tx.contract，再按 Method 与字符串参数列表调用对应变更。
func (d GovMutation) ExecCall(call *model.ContractCall) error {
	gov := NewGov(d.api)
	m := GovMutation{Gov: *gov}

	methodSel := call.Method
	args := call.Args
	switch methodSel {
	case [4]byte{0xdf, 0x60, 0xa5, 0x15}:
		if err := model.RequireArgLen(args, 1, "add_track"); err != nil {
			return err
		}
		track, err := model.DecodeScaleArgBytes[TrackData](args[0])
		if err != nil {
			return fmt.Errorf("add_track: %w", err)
		}
		return m.AddTrack(track)
	case [4]byte{0x46, 0xc4, 0x21, 0xdb}:
		if err := model.RequireArgLen(args, 1, "cancel_proposal"); err != nil {
			return err
		}
		proposalID, err := model.DecodeScaleArgBytes[uint32](args[0])
		if err != nil {
			return fmt.Errorf("cancel_proposal: proposalID: %w", err)
		}
		return m.CancelProposal(proposalID)
	case [4]byte{0x06, 0x99, 0x1e, 0x89}:
		if err := model.RequireArgLen(args, 1, "cancel_vote"); err != nil {
			return err
		}
		voteID, err := model.DecodeScaleArgBytes[uint64](args[0])
		if err != nil {
			return fmt.Errorf("cancel_vote: voteID: %w", err)
		}
		return m.CancelVote(voteID)
	case [4]byte{0xea, 0x58, 0xb3, 0x1d}:
		if err := model.RequireArgLen(args, 2, "deposit_proposal"); err != nil {
			return err
		}
		proposalID, err := model.DecodeScaleArgBytes[uint32](args[0])
		if err != nil {
			return fmt.Errorf("deposit_proposal: proposalID: %w", err)
		}
		amount, err := model.DecodeScaleArgBytes[model.Amount](args[1])
		if err != nil {
			return fmt.Errorf("deposit_proposal: amount: %w", err)
		}
		return m.DepositProposal(proposalID, amount)
	case [4]byte{0x3e, 0x44, 0x34, 0x0e}:
		if err := model.RequireArgLen(args, 1, "exec_proposal"); err != nil {
			return err
		}
		proposalID, err := model.DecodeScaleArgBytes[uint32](args[0])
		if err != nil {
			return fmt.Errorf("exec_proposal: proposalID: %w", err)
		}
		return m.ExecProposal(proposalID)
	case [4]byte{0x53, 0xe3, 0x90, 0x03}:
		return m.Init()
	case [4]byte{0xc6, 0xc8, 0x3a, 0xf9}:
		if err := model.RequireArgLen(args, 2, "join"); err != nil {
			return err
		}
		newUser, err := model.DecodeScaleArgBytes[model.UniAddr](args[0])
		if err != nil {
			return fmt.Errorf("join: newUser: %w", err)
		}
		balance, err := model.DecodeScaleArgBytes[model.Amount](args[1])
		if err != nil {
			return fmt.Errorf("join: balance: %w", err)
		}
		return m.Join(newUser, balance)
	case [4]byte{0x1f, 0xac, 0x3d, 0xd3}:
		return m.Leave()
	case [4]byte{0x8d, 0x6e, 0x0f, 0x8c}:
		return m.LeaveWithBurn()
	case [4]byte{0x9b, 0x7b, 0xfa, 0x69}:
		if err := model.RequireArgLen(args, 2, "mint"); err != nil {
			return err
		}
		to, err := model.DecodeScaleArgBytes[model.UniAddr](args[0])
		if err != nil {
			return fmt.Errorf("mint: to: %w", err)
		}
		value, err := model.DecodeScaleArgBytes[model.Amount](args[1])
		if err != nil {
			return fmt.Errorf("mint: value: %w", err)
		}
		return m.Mint(to, value)
	case [4]byte{0xa4, 0xf0, 0x19, 0x6c}:
		if err := model.RequireArgLen(args, 1, "payout"); err != nil {
			return err
		}
		spendID, err := model.DecodeScaleArgBytes[uint64](args[0])
		if err != nil {
			return fmt.Errorf("payout: spendID: %w", err)
		}
		return m.Payout(spendID)
	case [4]byte{0x6d, 0x6f, 0x07, 0x72}:
		return m.PublicJoin()
	case [4]byte{0x29, 0x87, 0xd4, 0xba}:
		if err := model.RequireArgLen(args, 1, "set_default_track"); err != nil {
			return err
		}
		trackID, err := model.DecodeScaleArgBytes[uint32](args[0])
		if err != nil {
			return fmt.Errorf("set_default_track: trackID: %w", err)
		}
		return m.SetDefaultTrack(trackID)
	case [4]byte{0x13, 0x64, 0x75, 0x15}:
		if err := model.RequireArgLen(args, 1, "set_public_join"); err != nil {
			return err
		}
		publicJoin, err := model.DecodeScaleArgBytes[bool](args[0])
		if err != nil {
			return fmt.Errorf("set_public_join: %w", err)
		}
		return m.SetPublicJoin(publicJoin)
	case [4]byte{0x87, 0x2c, 0x40, 0xe9}:
		if err := model.RequireArgLen(args, 3, "spend"); err != nil {
			return err
		}
		to, err := model.DecodeScaleArgBytes[model.UniAddr](args[0])
		if err != nil {
			return fmt.Errorf("spend: to: %w", err)
		}
		amount, err := model.DecodeScaleArgBytes[model.Amount](args[1])
		if err != nil {
			return fmt.Errorf("spend: amount: %w", err)
		}
		trackID, err := model.DecodeScaleArgBytes[uint32](args[2])
		if err != nil {
			return fmt.Errorf("spend: trackID: %w", err)
		}
		return m.Spend(to, amount, trackID)
	case [4]byte{0x1c, 0x04, 0x71, 0xc4}:
		if err := model.RequireArgLen(args, 2, "submit_proposal"); err != nil {
			return err
		}
		call, err := model.DecodeScaleArgBytes[CallContent](args[0])
		if err != nil {
			return fmt.Errorf("submit_proposal: call: %w", err)
		}
		trackID, err := model.DecodeScaleArgBytes[uint32](args[1])
		if err != nil {
			return fmt.Errorf("submit_proposal: trackID: %w", err)
		}
		return m.SubmitProposal(call, trackID)
	case [4]byte{0xbb, 0x5c, 0xa1, 0x28}:
		if err := model.RequireArgLen(args, 3, "submit_vote"); err != nil {
			return err
		}
		proposalID, err := model.DecodeScaleArgBytes[uint32](args[0])
		if err != nil {
			return fmt.Errorf("submit_vote: proposalID: %w", err)
		}
		opinionYes, err := model.DecodeScaleArgBytes[bool](args[1])
		if err != nil {
			return fmt.Errorf("submit_vote: opinionYes: %w", err)
		}
		lockAmount, err := model.DecodeScaleArgBytes[model.Amount](args[2])
		if err != nil {
			return fmt.Errorf("submit_vote: lockAmount: %w", err)
		}
		return m.SubmitVote(proposalID, opinionYes, lockAmount)
	case [4]byte{0xad, 0xa0, 0x64, 0x62}:
		if err := model.RequireArgLen(args, 2, "transfer"); err != nil {
			return err
		}
		to, err := model.DecodeScaleArgBytes[model.UniAddr](args[0])
		if err != nil {
			return fmt.Errorf("transfer: to: %w", err)
		}
		value, err := model.DecodeScaleArgBytes[model.Amount](args[1])
		if err != nil {
			return fmt.Errorf("transfer: value: %w", err)
		}
		return m.Transfer(to, value)
	case [4]byte{0xee, 0x3b, 0xc6, 0x85}:
		if err := model.RequireArgLen(args, 3, "transfer_from"); err != nil {
			return err
		}
		from, err := model.DecodeScaleArgBytes[model.UniAddr](args[0])
		if err != nil {
			return fmt.Errorf("transfer_from: from: %w", err)
		}
		to, err := model.DecodeScaleArgBytes[model.UniAddr](args[1])
		if err != nil {
			return fmt.Errorf("transfer_from: to: %w", err)
		}
		amount, err := model.DecodeScaleArgBytes[model.Amount](args[2])
		if err != nil {
			return fmt.Errorf("transfer_from: amount: %w", err)
		}
		return m.TransferFrom(from, to, amount)
	case [4]byte{0x2a, 0xb8, 0x1d, 0xd1}:
		if err := model.RequireArgLen(args, 1, "unlock"); err != nil {
			return err
		}
		voteID, err := model.DecodeScaleArgBytes[uint64](args[0])
		if err != nil {
			return fmt.Errorf("unlock: voteID: %w", err)
		}
		return m.Unlock(voteID)
	default:
		return fmt.Errorf("gov: unknown method %q", methodSel)
	}
}

// ExecuteQuery 按 method 将字符串参数解析为合约查询实参，返回 SCALE 编码结果。
func (q GovQuery) ExecQuery(call *model.ContractCall) ([]byte, error) {
	args := call.Args
	methodSel := call.Method
	switch methodSel {
	case [4]byte{0x87, 0xe0, 0xff, 0x32}:
		if err := model.RequireArgLen(args, 1, "balance_of"); err != nil {
			return nil, err
		}
		owner, err := model.DecodeScaleArgBytes[model.UniAddr](args[0])
		if err != nil {
			return nil, fmt.Errorf("balance_of: owner: %w", err)
		}
		out, err := q.BalanceOf(owner)
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case [4]byte{0x36, 0x26, 0xe9, 0xbf}:
		out, err := q.DefaultTrack()
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case [4]byte{0x76, 0xf2, 0x07, 0x24}:
		out, err := q.GetPublicJoin()
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case [4]byte{0x3c, 0xd4, 0x96, 0x6d}:
		if err := model.RequireArgLen(args, 1, "lock_balance_of"); err != nil {
			return nil, err
		}
		owner, err := model.DecodeScaleArgBytes[model.UniAddr](args[0])
		if err != nil {
			return nil, fmt.Errorf("lock_balance_of: owner: %w", err)
		}
		out, err := q.LockBalanceOf(owner)
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case [4]byte{0x53, 0x55, 0x0f, 0x05}:
		out, err := q.Members()
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case [4]byte{0x79, 0x9f, 0xe2, 0xdd}:
		if err := model.RequireArgLen(args, 1, "proposal"); err != nil {
			return nil, err
		}
		id, err := model.DecodeScaleArgBytes[uint32](args[0])
		if err != nil {
			return nil, fmt.Errorf("proposal: id: %w", err)
		}
		out, err := q.Proposal(id)
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case [4]byte{0xfd, 0x88, 0x90, 0x7b}:
		if err := model.RequireArgLen(args, 1, "proposal_status"); err != nil {
			return nil, err
		}
		id, err := model.DecodeScaleArgBytes[uint32](args[0])
		if err != nil {
			return nil, fmt.Errorf("proposal_status: id: %w", err)
		}
		out, err := q.ProposalStatus(id)
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case [4]byte{0xfe, 0x26, 0xfd, 0x17}:
		out, err := q.Proposals()
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case [4]byte{0x77, 0x17, 0x71, 0xf7}:
		out, err := q.TotalSupply()
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case [4]byte{0xb9, 0xfd, 0x54, 0xc4}:
		if err := model.RequireArgLen(args, 1, "track"); err != nil {
			return nil, err
		}
		id, err := model.DecodeScaleArgBytes[uint32](args[0])
		if err != nil {
			return nil, fmt.Errorf("track: id: %w", err)
		}
		out, err := q.Track(id)
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case [4]byte{0x3c, 0x05, 0xbe, 0x89}:
		out, err := q.Tracks()
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case [4]byte{0x4d, 0x15, 0x1c, 0xf1}:
		if err := model.RequireArgLen(args, 1, "vote"); err != nil {
			return nil, err
		}
		id, err := model.DecodeScaleArgBytes[uint64](args[0])
		if err != nil {
			return nil, fmt.Errorf("vote: id: %w", err)
		}
		out, err := q.Vote(id)
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	case [4]byte{0x34, 0x0f, 0x2c, 0xf4}:
		out, err := q.Votes()
		if err != nil {
			return nil, err
		}
		return codec.Encode(out)
	default:
		return nil, fmt.Errorf("gov: unknown query method %q", methodSel)
	}
}

func NewGov(api model.ContractApi) *Gov {
	return &Gov{
		api:                 api,
		members:             &model.StoreMapping[model.UniAddr, model.Amount]{Namespace: "gov", KeyPrefix: "member_"},
		publicJoin:          &model.StoreValue[bool]{Namespace: "gov", Key: "public_join"},
		transferEnabled:     &model.StoreValue[bool]{Namespace: "gov", Key: "transfer_enabled"},
		totalIssuance:       &model.StoreValue[model.Amount]{Namespace: "gov", Key: "total_issuance"},
		defaultTrack:        &model.StoreValue[uint32]{Namespace: "gov", Key: "default_track"},
		nextProposalIDStore: &model.StoreValue[uint32]{Namespace: "gov", Key: "next_proposal_id"},
		nextVoteIDStore:     &model.StoreValue[uint64]{Namespace: "gov", Key: "next_vote_id"},
		nextSpendIDStore:    &model.StoreValue[uint64]{Namespace: "gov", Key: "next_spend_id"},
		nextTrackIDStore:    &model.StoreValue[uint32]{Namespace: "gov", Key: "next_track_id"},
		memberLocks:         &model.StoreMapping[model.UniAddr, model.Amount]{Namespace: "gov", KeyPrefix: "member_lock_"},
		allowances:          &model.StoreMapping[model.UniAddr, model.Amount]{Namespace: "gov", KeyPrefix: "allowance_"},
		tracks:              &model.StoreMapping[uint32, TrackData]{Namespace: "gov", KeyPrefix: "track_"},
		proposals:           &model.StoreMapping[uint32, Proposal]{Namespace: "gov", KeyPrefix: "proposal_v2"},
		votes:               &model.StoreMapping[uint64, Vote]{Namespace: "gov", KeyPrefix: "vote_"},
		voteUnlocks:         &model.StoreMapping[uint64, bool]{Namespace: "gov", KeyPrefix: "vote_unlock_"},
		spends:              &model.StoreMapping[uint64, Spend]{Namespace: "gov", KeyPrefix: "spend_"},
	}
}
