// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// 环境变量
// Environments
type Env struct {
	Envs  []*Kvalue `json:"envs"`
	Files []*Kvalue `json:"files"`
}

type Kvalue struct {
	K string `json:"k"`
	V string `json:"v"`
}

// 加密值
// Secret value
type LenValue struct {
	K string `json:"k"`
	V int    `json:"v"`
}

type Mutation struct {
}

type Query struct {
}

// 加密环境变量
// Encrypt environment variables
type SecretEnv struct {
	Envs  []*LenValue `json:"envs"`
	Files []*LenValue `json:"files"`
}

type SecretEnvWithHash struct {
	Hash   string     `json:"hash"`
	Secret *SecretEnv `json:"secret"`
}
