// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChainInfo struct {
	IsMain         bool   `json:"is_main"`
	CloudContract  string `json:"cloud_contract"`
	SubnetContract string `json:"subnet_contract"`
	// 展示用网络名称（如 Paseo / Polkadot）
	NetworkLabel string `json:"network_label"`
}

// 环境变量
// Environments
type Kvalue struct {
	K string `json:"k"`
	V string `json:"v"`
}

// 加密值
// Secret value
type LenValue struct {
	K string `json:"k"`
	V int    `json:"v"`
}

type Mutation struct {
}

type Query struct {
}

// 加密环境变量
// Encrypt environment variables
type SecretEnv struct {
	Envs  []*LenValue `json:"envs"`
	Files []*LenValue `json:"files"`
}

type SecretEnvWithHash struct {
	Hash   string     `json:"hash"`
	Secret *SecretEnv `json:"secret"`
}
